### ISSUE TITLE
Curios from this mod go back to inventory after death (more details in desc.)

### ISSUE THREAD

**Issue by AronRiggx** [LordDDiamond/Piglet-Structures-mod#1]
Hello! Started a new playthrough recently with this mod and I noticed that even with keepInventory enabled and the "Keep Curios equipped" setting enabled in Curios API's advanced config, the curios keep falling out, I went to a creative world and tested it with every curio and all of them go back to the inventory after death.

The real problem I saw is as follows though:
Opening up the Curios page after death reveals that the Curios are (what I'm calling) "ghost-equipped", like they're not really equipped but they're occupying a slot. Opening and closing the inventory a bunch somewhat fixes this but also sometimes breaks it entirely, resulting in duplicates of the equipped curios.

Hope this report helps! I love the mod btw. <3

**Comment by LordDDiamond** [comment]
Hi! Sorry, it took so long to respond. I have made a series of tests in different modpacks and asked some people to do so as well, but we weren't able to reproduce the bug.

I've tried it with the "Keep Curios equipped" option in the Curios API config, with the keepInventory gamerule and with the Corpse mod.

Everything was fine each time.

My conclusion then is that the problem is in some other mod that affects curios.

Thanks for reporting the potential issue and I'm glad that You love the mod ;D
